emikoKanri/urls.py
from django.urls import path
from . import views
app_name= 'emikoKanri'

urlpatterns = [
    path('', views.nurse_list, name='nurse_list'),
    path('nurse/<int:pk>/', views.nurse_detail, name='nurse_detail'),
    path('nurse/new/', views.nurse_new, name='nurse_new'),
    path('nurse/<int:pk>/edit/', views.nurse_edit, name='nurse_edit'),
    path('nurse/<pk>/remove/', views.nurse_remove, name='nurse_remove'),
]

emikoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('emikoKanri.urls')),
    path('post/', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views
app_name= 'post'
urlpatterns = [
    path('post/list/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
]

emikoKanri/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class NurseRecord(models.Model):
    nurse_day = models.DateField()
    urine_time = models.CharField(max_length=5, null=True)
    urine_volume = models.PositiveIntegerField(null=True)
    memo = models.CharField(max_length=500, null=True)
    def __str__(self):
        return self.memo

 

emikoKanri/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from .models import NurseRecord

class NurseRecordForm(forms.ModelForm):

    class Meta:
        model = NurseRecord
        fields = ('nurse_day', 'urine_time', 'urine_volume', 'memo')
        widgets = {
            'memo': Textarea(attrs={'cols': 50, 'rows': 4}),
        }
        # 'memo': Textarea(attrs={'cols': 80, 'rows': 20}),

emikoKanri/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.utils import timezone
from .models import NurseRecord
from .forms import NurseRecordForm
# Create your views here.
def paginate_queryset(request, queryset, count):
    """Pageオブジェクトを返す。

    ページングしたい場合に利用してください。

    countは、1ページに表示する件数です。
    返却するPgaeオブジェクトは、以下のような感じで使えます。

        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}

    また、page_obj.object_list で、count件数分の絞り込まれたquerysetが取得できます。

    """
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj
def nurse_list(request):
    nurses = NurseRecord.objects.all().order_by('-nurse_day')
    page_obj = paginate_queryset(request, nurses, 10)
    return render(request, 'emikoKanri/nurse_list.html', {'page_obj':page_obj})
def nurse_detail(request, pk):
    nurse = get_object_or_404(NurseRecord, pk=pk)
    return render(request, 'emikoKanri/nurse_detail.html', {'nurse': nurse})
@login_required
def nurse_new(request):
    if request.method == "POST":
        form = NurseRecordForm(request.POST)
        if form.is_valid():
            nurse = form.save(commit=False)
            nurse.author = request.user
            
            nurse.save()
            return redirect('emikoKanri:nurse_list')
    else:
        form = NurseRecordForm()
    return render(request, 'emikoKanri/nurse_edit.html', {'form': form})
@login_required
def nurse_edit(request, pk):
    nurse = get_object_or_404(NurseRecord, pk=pk)
    if request.method == "POST":
        form = NurseRecordForm(request.POST, instance=nurse)
        if form.is_valid():
            nurse = form.save(commit=False)
            nurse.author = request.user
            
            nurse.save()
            return redirect('emikoKanri:nurse_list')
    else:
        form = NurseRecordForm(instance=nurse)
    return render(request, 'emikoKanri/nurse_edit.html', {'form': form})

@login_required
def nurse_remove(request, pk):
    nurse = get_object_or_404(NurseRecord, pk=pk)
    nurse.delete()
    return redirect('emikoKanri:nurse_list')

templates/emikoKanri/nurse_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>尿バルーン　クリア</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/emikoKanri/nurse_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="xpaging">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
        {% endif %}
    
        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <span>{{ num }}</span>
            {% else %}
                <a href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
    
        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">次へ</a>
        {% endif %}
        
    </div>
    <table border="1">
        <tr>
            <th>日付</th>
            <th>時間</th>
            <th>尿量</th>
            <th>メモ</th>

            
        </tr>
            {% for nurse in page_obj %}
            <tr>
            <td>{{ nurse.nurse_day }}</td>
            <td>{{ nurse.urine_time }}</td>
            <td>{{ nurse.urine_volume }}</td>
            <td>{{ nurse.memo }}</td>
           
            
            {% if user.is_superuser %}
                
                <td><a href="{% url 'emikoKanri:nurse_edit' nurse.pk %}">更新画面</a></td> 
                <td><a href="{% url 'emikoKanri:nurse_remove' nurse.pk %}">削除画面</a></td> 
                    
            {% endif %}  
            
            
            </tr>

            {% endfor %}
    </table>


    
{% endblock %}