emikoKanri/urls.py
from django.urls import path
from . import views
app_name= 'emikoKanri'

urlpatterns = [
    path('', views.nurse_list, name='nurse_list'),
    path('nurse/<int:pk>/', views.nurse_detail, name='nurse_detail'),
    path('nurse/new/', views.nurse_new, name='nurse_new'),
    path('nurse/<int:pk>/edit/', views.nurse_edit, name='nurse_edit'),
    path('nurse/<pk>/remove/', views.nurse_remove, name='nurse_remove'),
]

emikoSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('emikoKanri.urls')),
    path('post/', include('post.urls')),
]

post/urls.py
from django.urls import path
from . import views
app_name= 'post'
urlpatterns = [
    path('post/list/', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
]

templates/base.html
{% load static %}
<html>
    <head>
        <title>Emiko kiroku</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/emikoKanri.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'emikoKanri:nurse_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'logout' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <a href="{% url 'post:post_list' %}" class="top-menu">連絡に行く</a>
            
            <h1><a href="/">Emiko 尿記録</a></h1>

            
        </div>
        
        <div class="content container">
            <div class="row">
                <div class="col-lg-12">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

templates/base2.html
{% load static %}
<html>
    <head>
        <title>Emiko renraku</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/emikoKanri.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'post:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'post:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'logout' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <a href="{% url 'emikoKanri:nurse_list' %}" class="top-menu">尿記録に行く</a>
            
            <h1><a href="/">Emiko 連絡記録</a></h1>

            
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>